var guests = ['Baby Mahnoor', 'Aapi Areeba', 'Aneela'];
console.log("Hi ".concat(guests[0], ". \nHope this message finds you in good health. \nHey, we are organizing our baby's 5th birthday this weekend on Sunday at 06:00 pm.\nYou are invited to attend your friend's birthday party with Mom and Pop. Please come and we'll enjoy.\nBaby Abeel's Mom.\n"));
console.log("Assalam o alaikum ".concat(guests[1], "!\nI hope and pray that you are fine by grace of Allah.\nWe'll be having a birthday party on next Friday for . \nI am writing this to invite you to my birthday party this Friday.\nPlease join us to wish the little baby.\nBaby Abeel Family.\n"));
console.log("Good morning ".concat(guests[2], ", \nI am writing this to invite you to the birthday party for baby Abeel.\nAwaiting your confirmation.\nThanks.\nAbeel and Family.\n"));
console.log("---------------------------------------------------------------------------------\n");
var guestWhoCantMakeIt = guests[2];
console.log("".concat(guestWhoCantMakeIt, " will not be able to make it to the party."));
console.log("---------------------------------------------------------------------------------\n");
var newGuest1 = 'Haroon';
guests[2] = newGuest1;
console.log("Reminder... \nHi ".concat(guests[0], ", there is a party on Friday.\n"));
console.log("Reminder... \nHi ".concat(guests[1], ", there is a party on Friday.\n"));
console.log("Good morning ".concat(guests[2], ", \nI am writing this to invite you to the birthday party for baby Abeel.\nEven though not much is left. Still hoping that you will make it.\nThanks.\nBaby Abeel and Family.\n"));
